### ISSUE TITLE
Improve importing, fix importing panic

### ISSUE THREAD

**Issue by kevinburke** [gopherds/gophernotes#34]
Steps to reproduce (maybe?)

- set JUPYTER_CONFIG_DIR to $HOME/cfg/jupyter
- set JUPYTER_DATA_DIR to $HOME/local/share/jupyter
- run `go install ./...` (I'm using go1.7)

start Jupyter Notebook, start a Golang notebook

type the following

```go
 import "fmt"
fmt.Println("Hello World")
```

Then hit shift+enter. I get the following panic:

```
panic: exit status 2

goroutine 1 [running]:
panic(0x42ebe80, 0xc420288f60)
	/Users/kevin/go/src/runtime/panic.go:500 +0x1a1
github.com/gopherds/gophernotes/internal/repl.(*Session).Eval(0xc4200ac370, 0xc420284c90, 0x27, 0xc42022d498, 0xc420286d70, 0x8, 0xc420288500, 0x0, 0x0, 0x0, ...)
	/Users/kevin/code/go/src/github.com/gopherds/gophernotes/internal/repl/repl.go:355 +0xc01
main.HandleExecuteRequest(0xc4202884e0, 0x20, 0xc420286c98, 0x8, 0xc420288500, 0x20, 0xc420286ca0, 0xf, 0x0, 0x0, ...)
	/Users/kevin/code/go/src/github.com/gopherds/gophernotes/execution.go:60 +0x2f3
main.HandleShellMsg(0xc4202884e0, 0x20, 0xc420286c98, 0x8, 0xc420288500, 0x20, 0xc420286ca0, 0xf, 0x0, 0x0, ...)
	/Users/kevin/code/go/src/github.com/gopherds/gophernotes/gophernotes.go:108 +0x2c7
main.RunKernel(0x7fff5fbff495, 0x59, 0x44ab360, 0xc4200142a8)
	/Users/kevin/code/go/src/github.com/gopherds/gophernotes/gophernotes.go:194 +0x836
main.main()
	/Users/kevin/code/go/src/github.com/gopherds/gophernotes/main.go:25 +0xc6
```

Haven't investigated it at all.

**Comment by kevinburke** [comment]
More debugging info:

```
Error running goimports:
/var/folders/dx/x6gx95t14n7bb3v878968fkm0000gn/T/448556322/func_proxy.go:5:1: expected declaration, found 'IDENT' fmt
panic: exit status 2
```

It would be nice to surface that in the UI somehow

**Comment by dwhitena** [comment]
I think the problem here is the import.  As of now you need to use `:import` to import.  However, we should just throw an error or message if we get the import without the colon, not panic.  Thanks!

**Comment by dwhitena** [comment]
https://github.com/gopherds/gophernotes/pull/35 allows a user to have more insight into this error.  However, we should improve the importing process, such that this doesn't crash the kernel.

**Comment by dwhitena** [comment]
Also, we should improve imports, as multiple imports in the same cell can result in error.

**Comment by kevinburke** [comment]
> multiple imports in the same cell can result in error.

Ah, I just hit this.

This fails:

```
:import "time"
:import "fmt"
t := time.Time{}
fmt.Println(t.IsZero())
t.IsZero()
```

with the following message in the terminal:

```
$ jupyter notebook
[I 10:32:50.249 NotebookApp] Serving notebooks from local directory: /Users/kevin/code/go/src/github.com/kevinburke/go-notebooks
[I 10:32:50.251 NotebookApp] 0 active kernels
[I 10:32:50.251 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 10:32:50.251 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 10:32:54.140 NotebookApp] 404 GET /api/kernels/c25e3582-c84b-4e46-a2c7-d35ecfc6058d/channels?session_id=D5E3D94A13E040CDAA2F3C2D1F669EFC (::1): Kernel does not exist: c25e3582-c84b-4e46-a2c7-d35ecfc6058d
[W 10:32:54.236 NotebookApp] 404 GET /api/kernels/c25e3582-c84b-4e46-a2c7-d35ecfc6058d/channels?session_id=D5E3D94A13E040CDAA2F3C2D1F669EFC (::1) 163.82ms referer=None
[W 10:33:03.351 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js (::1) 15.83ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[I 10:33:03.741 NotebookApp] Kernel started: 7d3a8201-0b07-4576-8893-27409f786da4
[I 10:33:15.760 NotebookApp] Kernel shutdown: 7d3a8201-0b07-4576-8893-27409f786da4
[I 10:33:15.901 NotebookApp] Kernel started: ad224100-35e3-49ba-a536-727aabeb1c3d
[I 10:33:16.129 NotebookApp] Adapting to protocol v4.0 for kernel ad224100-35e3-49ba-a536-727aabeb1c3d
error: import: can't find import:
error: import: can't find import:
```

Should I open a different ticket?

**Comment by dwhitena** [comment]
@kevinburke No, I'm working on this now and will address in this ticket.  I've got multiple imports working, just checking a few things.  Will PR soon.

**Comment by dwhitena** [comment]
@kevinburke Addressed by https://github.com/gopherds/gophernotes/pull/36

**Comment by dwhitena** [comment]
Closing.
