### ISSUE TITLE
error relative path /go/bin/gophernote

### ISSUE THREAD

**Issue by cocodrino** [gopherds/gophernotes#46]
Hi..I'm having the following issue

```shell

404 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 17.28ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=gophernotes
[E 12:14:57.069 NotebookApp] Failed to run command:
    ['/go/bin/gophernotes', '/run/user/1001/jupyter/kernel-9211b0e6-8d3c-4252-a796-0e84361e6ce2.json']
    with kwargs:
    {'stdout': None, 'stderr': None, 'start_new_session': True, 'stdin': -1, 'cwd': '/home/yo/Documentos/proyectos/clojure', 'env': {'PHPBREW_ROOT': '/home/yo/.phpbrew', 'PHPBREW_LOOKUP_PREFIX': '', 'PHPBREW_PHP': 'php-5.6.22', 'GDMSESSION': 'gnome-classic', 'MAIL': '/var/spool/mail/yo', 'SBT_OPTS': '-Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled  -Duser.timezone=GMT', 'SHLVL': '1', 'XDG_SESSION_TYPE': 'x11', 'SHELL': '/bin/zsh', 'MOZ_PLUGIN_PATH': '/usr/lib/mozilla/plugins', 'EDITOR': 'nano', 'QT_QPA_PLATFORMTHEME': 'qgnomeplatform', 'GTK_MODULES': 'canberra-gtk-module', 'HG': '/usr/bin/hg', 'USER': 'yo', 'TERM': 'xterm-256color', 'HOME': '/home/yo', 'ANT_HOME': '/usr/share/apache-ant', 'DESKTOP_SESSION': 'gnome-classic', 'GSETTINGS_SCHEMA_DIR': '/home/yo/data', 'GNOME_SHELL_SESSION_MODE': 'classic', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'VTE_VERSION': '4203', '_': '/usr/bin/jupyter', 'SESSION_MANAGER': 'local/yo-pc:@/tmp/.ICE-unix/932,unix/yo-pc:/tmp/.ICE-unix/932', 'GOPATH': '/home/yo/Documentos/proyectos/go', 'PHPBREW_PATH': '/home/yo/.phpbrew/php/php-5.6.22/bin', 'XDG_SEAT': 'seat0', 'SSH_AUTH_SOCK': '/run/user/1001/keyring/ssh', 'DISPLAY': ':0', 'BROWSER': '/usr/bin/google-chrome-stable', 'PATH': '/home/yo/comandos:/home/yo/.phpbrew/php/php-5.6.22/bin:/home/yo/.phpbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/yo/Documentos/proyectos/go/bin', 'PHPBREW_VERSION_REGEX': '^([[:digit:]]+\\.){2}[[:digit:]]+$', 'PWD': '/home/yo/Documentos/proyectos/clojure', 'OLDPWD': '/home/yo/Documentos/proyectos/clojure/parser', 'XDG_VTNR': '2', 'GDM_LANG': 'es_ES.UTF-8', 'LOGNAME': 'yo', 'WINDOWID': '29360134', 'XDG_MENU_PREFIX': 'gnome-', 'XDG_RUNTIME_DIR': '/run/user/1001', 'JPY_PARENT_PID': '14559', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1001/bus', 'XDG_SESSION_ID': 'c2', 'LANG': 'es_ES.UTF-8', 'AUTOJUMP_SOURCED': '1', 'PHPBREW_HOME': '/home/yo/.phpbrew', 'XAUTHORITY': '/run/user/1001/gdm/Xauthority', 'PATH_WITHOUT_PHPBREW': '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl', 'AUTOJUMP_ERROR_PATH': '/home/yo/.local/share/autojump/errors.log', 'XDG_CURRENT_DESKTOP': 'GNOME-Classic:GNOME', 'WINDOWPATH': '2', 'XDG_SESSION_DESKTOP': 'gnome-classic', 'USERNAME': 'yo', 'PHPBREW_BIN': '/home/yo/.phpbrew/bin'}}
    
[E 12:14:57.071 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_name)
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/usr/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/usr/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '/go/bin/gophernotes'
[E 12:14:57.091 NotebookApp] {
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
      "Origin": "http://localhost:8888",
      "Content-Type": "application/json",
      "Host": "localhost:8888",
      "Accept-Encoding": "gzip, deflate",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=gophernotes",
      "Accept-Language": "es,en-CA;q=0.8,en;q=0.6",
      "Content-Length": "80",
      "Accept": "application/json, text/javascript, */*; q=0.01"
    }
[E 12:14:57.092 NotebookApp] 500 POST /api/sessions (::1) 169.37ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=gophernotes
[W 12:16:00.779 NotebookApp] 404 GET /static/components/backbone/backbone-min.map (::1) 2.53ms referer=None
[I 12:16:56.976 NotebookApp] Saving file at /Untitled.ipynb
[W 12:17:38.556 NotebookApp] 404 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 3.57ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=gophernotes
[E 12:17:39.757 NotebookApp] Failed to run command:
    ['/go/bin/gophernotes', '/run/user/1001/jupyter/kernel-c91df6b9-3cdf-4613-ad84-bd6bfc8fe9e9.json']
    with kwargs:
    {'stdout': None, 'stderr': None, 'start_new_session': True, 'stdin': -1, 'cwd': '/home/yo/Documentos/proyectos/clojure', 'env': {'PHPBREW_ROOT': '/home/yo/.phpbrew', 'PHPBREW_LOOKUP_PREFIX': '', 'PHPBREW_PHP': 'php-5.6.22', 'GDMSESSION': 'gnome-classic', 'MAIL': '/var/spool/mail/yo', 'SBT_OPTS': '-Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled  -Duser.timezone=GMT', 'SHLVL': '1', 'XDG_SESSION_TYPE': 'x11', 'SHELL': '/bin/zsh', 'MOZ_PLUGIN_PATH': '/usr/lib/mozilla/plugins', 'EDITOR': 'nano', 'QT_QPA_PLATFORMTHEME': 'qgnomeplatform', 'GTK_MODULES': 'canberra-gtk-module', 'HG': '/usr/bin/hg', 'USER': 'yo', 'TERM': 'xterm-256color', 'HOME': '/home/yo', 'ANT_HOME': '/usr/share/apache-ant', 'DESKTOP_SESSION': 'gnome-classic', 'GSETTINGS_SCHEMA_DIR': '/home/yo/data', 'GNOME_SHELL_SESSION_MODE': 'classic', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'VTE_VERSION': '4203', '_': '/usr/bin/jupyter', 'SESSION_MANAGER': 'local/yo-pc:@/tmp/.ICE-unix/932,unix/yo-pc:/tmp/.ICE-unix/932', 'GOPATH': '/home/yo/Documentos/proyectos/go', 'PHPBREW_PATH': '/home/yo/.phpbrew/php/php-5.6.22/bin', 'XDG_SEAT': 'seat0', 'SSH_AUTH_SOCK': '/run/user/1001/keyring/ssh', 'DISPLAY': ':0', 'BROWSER': '/usr/bin/google-chrome-stable', 'PATH': '/home/yo/comandos:/home/yo/.phpbrew/php/php-5.6.22/bin:/home/yo/.phpbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/yo/Documentos/proyectos/go/bin', 'PHPBREW_VERSION_REGEX': '^([[:digit:]]+\\.){2}[[:digit:]]+$', 'PWD': '/home/yo/Documentos/proyectos/clojure', 'OLDPWD': '/home/yo/Documentos/proyectos/clojure/parser', 'XDG_VTNR': '2', 'GDM_LANG': 'es_ES.UTF-8', 'LOGNAME': 'yo', 'WINDOWID': '29360134', 'XDG_MENU_PREFIX': 'gnome-', 'XDG_RUNTIME_DIR': '/run/user/1001', 'JPY_PARENT_PID': '14559', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1001/bus', 'XDG_SESSION_ID': 'c2', 'LANG': 'es_ES.UTF-8', 'AUTOJUMP_SOURCED': '1', 'PHPBREW_HOME': '/home/yo/.phpbrew', 'XAUTHORITY': '/run/user/1001/gdm/Xauthority', 'PATH_WITHOUT_PHPBREW': '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl', 'AUTOJUMP_ERROR_PATH': '/home/yo/.local/share/autojump/errors.log', 'XDG_CURRENT_DESKTOP': 'GNOME-Classic:GNOME', 'WINDOWPATH': '2', 'XDG_SESSION_DESKTOP': 'gnome-classic', 'USERNAME': 'yo', 'PHPBREW_BIN': '/home/yo/.phpbrew/bin'}}
    
[E 12:17:39.757 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_name)
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/usr/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/usr/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '/go/bin/gophernotes'
[E 12:17:39.760 NotebookApp] {
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
      "Origin": "http://localhost:8888",
      "Content-Type": "application/json",
      "Host": "localhost:8888",
      "Accept-Encoding": "gzip, deflate",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=gophernotes",
      "Accept-Language": "es,en-CA;q=0.8,en;q=0.6",
      "Content-Length": "80",
      "Accept": "application/json, text/javascript, */*; q=0.01"
    }
[E 12:17:39.760 NotebookApp] 500 POST /api/sessions (::1) 26.21ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=gophernotes
^C[I 12:17:46.038 NotebookApp] interrupted
Serving notebooks from local directory: /home/yo/Documentos/proyectos/clojure
0 active kernels 
The Jupyter Notebook is running at: http://localhost:8888/
Shutdown this notebook server (y/[n])? y
[C 12:17:48.767 NotebookApp] Shutdown confirmed
[I 12:17:48.767 NotebookApp] Shutting down kernels
 yo  ~  Documentos  proyectos  clojure  jupyter notebook
[I 12:17:51.802 NotebookApp] Serving notebooks from local directory: /home/yo/Documentos/proyectos/clojure
[I 12:17:51.803 NotebookApp] 0 active kernels 
[I 12:17:51.803 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 12:17:51.803 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Se ha abierto una nueva ventana en la sesión actual del navegador.
[I 12:17:58.287 NotebookApp] Creating new notebook in 
[W 12:17:58.800 NotebookApp] 404 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 21.05ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=gophernotes
[E 12:17:59.866 NotebookApp] Failed to run command:
    ['/go/bin/gophernotes', '/run/user/1001/jupyter/kernel-0f8518f6-3a4c-4ca0-89db-59aab477f12a.json']
    with kwargs:
    {'stderr': None, 'env': {'ANT_HOME': '/usr/share/apache-ant', 'XDG_VTNR': '2', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'USER': 'yo', 'HOME': '/home/yo', 'VTE_VERSION': '4203', 'XAUTHORITY': '/run/user/1001/gdm/Xauthority', 'AUTOJUMP_SOURCED': '1', 'GNOME_SHELL_SESSION_MODE': 'classic', 'LANG': 'es_ES.UTF-8', 'HG': '/usr/bin/hg', 'QT_QPA_PLATFORMTHEME': 'qgnomeplatform', 'SESSION_MANAGER': 'local/yo-pc:@/tmp/.ICE-unix/932,unix/yo-pc:/tmp/.ICE-unix/932', 'PHPBREW_PATH': '/home/yo/.phpbrew/php/php-5.6.22/bin', 'DESKTOP_SESSION': 'gnome-classic', 'PHPBREW_VERSION_REGEX': '^([[:digit:]]+\\.){2}[[:digit:]]+$', 'SHELL': '/bin/zsh', 'XDG_SESSION_ID': 'c2', 'SSH_AUTH_SOCK': '/run/user/1001/keyring/ssh', 'EDITOR': 'nano', 'AUTOJUMP_ERROR_PATH': '/home/yo/.local/share/autojump/errors.log', 'WINDOWID': '29360134', 'PATH': '/home/yo/comandos:/home/yo/.phpbrew/php/php-5.6.22/bin:/home/yo/.phpbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/yo/Documentos/proyectos/go/bin', 'MOZ_PLUGIN_PATH': '/usr/lib/mozilla/plugins', 'USERNAME': 'yo', 'XDG_SESSION_DESKTOP': 'gnome-classic', 'OLDPWD': '/home/yo/Documentos/proyectos/clojure/parser', 'PHPBREW_ROOT': '/home/yo/.phpbrew', 'WINDOWPATH': '2', 'TERM': 'xterm-256color', 'PHPBREW_BIN': '/home/yo/.phpbrew/bin', 'GDM_LANG': 'es_ES.UTF-8', 'GOPATH': '/home/yo/Documentos/proyectos/go', 'XDG_RUNTIME_DIR': '/run/user/1001', 'PHPBREW_HOME': '/home/yo/.phpbrew', '_': '/usr/bin/jupyter', 'JPY_PARENT_PID': '14737', 'BROWSER': '/usr/bin/google-chrome-stable', 'PATH_WITHOUT_PHPBREW': '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl', 'SHLVL': '1', 'XDG_SESSION_TYPE': 'x11', 'XDG_SEAT': 'seat0', 'LOGNAME': 'yo', 'GTK_MODULES': 'canberra-gtk-module', 'XDG_MENU_PREFIX': 'gnome-', 'MAIL': '/var/spool/mail/yo', 'PHPBREW_PHP': 'php-5.6.22', 'SBT_OPTS': '-Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled  -Duser.timezone=GMT', 'PWD': '/home/yo/Documentos/proyectos/clojure', 'GSETTINGS_SCHEMA_DIR': '/home/yo/data', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1001/bus', 'GDMSESSION': 'gnome-classic', 'DISPLAY': ':0', 'XDG_CURRENT_DESKTOP': 'GNOME-Classic:GNOME', 'PHPBREW_LOOKUP_PREFIX': ''}, 'cwd': '/home/yo/Documentos/proyectos/clojure', 'stdout': None, 'stdin': -1, 'start_new_session': True}
    
[E 12:17:59.866 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_name)
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/usr/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/usr/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '/go/bin/gophernotes'
[E 12:17:59.874 NotebookApp] {
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "Connection": "keep-alive",
      "Host": "localhost:8888",
      "Content-Type": "application/json",
      "Content-Length": "81",
      "Origin": "http://localhost:8888",
      "Referer": "http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=gophernotes",
      "Accept-Language": "es,en-CA;q=0.8,en;q=0.6",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
      "Accept-Encoding": "gzip, deflate"
    }
[E 12:17:59.875 NotebookApp] 500 POST /api/sessions (::1) 72.57ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=gophernotes




```

kernel error

```python


Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_name)
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/go/bin/gophernotes'

```

I'm not sure but I think than probably the error is because jupyter is trying to found the gophernotes binary inside /go/bin/gophernote (I don't know what is the root foolder for this relative path) and it's fails because my gophernotes is inside ~/Documents/projecs/go/bin/gophernotes

what could be the best way for solve it? thank you so much!!!

**Comment by dwhitena** [comment]
Hi @cocodrino!  Can you run `gophernotes` the binary directly from within a terminal?  If so, is it actually located at `/go/bin/gophernotes`?  You might need to update the path to the binary in the `kernel.json` file.

**Comment by sbinet** [comment]
note that #45 can actually deal with that.
It seems to me that `Jupyter` will actually apply a "logical" `which` on the given `argv`...

**Comment by dwhitena** [comment]
Thanks @sbinet merged.  @cocodrino can you confirm that this fixes the issue?

**Comment by dwhitena** [comment]
Going to close this assuming @sbinet's PR deals with it.  @cocodrino please let us know if you are still having issues.
